export const REGISTER_CLINIC_REQUEST = 'REGISTER_CLINIC_REQUEST';
export const REGISTER_CLINIC_SUCCESS = 'REGISTER_CLINIC_SUCCESS';
export const REGISTER_CLINIC_FAILURE = 'REGISTER_CLINIC_FAILURE';

export const DELETE_CLINIC_REQUEST = 'DELETE_CLINIC_REQUEST';
export const DELETE_CLINIC_SUCCESS = 'DELETE_CLINIC_SUCCESS';
export const DELETE_CLINIC_FAILURE = 'DELETE_CLINIC_FAILURE';

export const UPDATE_CLINIC_REQUEST = 'UPDATE_CLINIC_REQUEST';
export const UPDATE_CLINIC_SUCCESS = 'UPDATE_CLINIC_SUCCESS';
export const UPDATE_CLINIC_FAILURE = 'UPDATE_CLINIC_FAILURE';

export const GET_CLINIC_DETAILS_REQUEST = 'GET_CLINIC_DETAILS_REQUEST';
export const GET_CLINIC_DETAILS_SUCCESS = 'GET_CLINIC_DETAILS_SUCCESS';
export const GET_CLINIC_DETAILS_FAILURE = 'GET_CLINIC_DETAILS_FAILURE';

export const GET_ALL_CLINIC_REQUEST = 'GET_ALL_CLINIC_REQUEST';
export const GET_ALL_CLINIC_SUCCESS = 'GET_ALL_CLINIC_SUCCESS';
export const GET_ALL_CLINIC_FAILURE = 'GET_ALL_CLINIC_FAILURE';
